<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreTableroElectricoRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'solicitud_id' => 'required|exists:solicituds,id',
            'tension_operacion' => 'nullable|string',
            'corriente_nominal' => 'nullable|string',
            'elemento_maniobra' => 'nullable|string',
            'fabricante' => 'nullable|string',
            'tipo_aplicacion' => 'nullable|string',
            'control_ats' => 'nullable|string',
            'tipo_servicio' => 'required|string',
            'observaciones_iniciales' => 'nullable|string',
            'gabinete' => 'nullable|string',
            'puertas' => 'nullable|string',
            'cerraduras' => 'nullable|string',
            'bisagras' => 'nullable|string',
            'limpieza_general' => 'nullable|string',
            'pilotos_indicadores' => 'nullable|string',
            'selectores' => 'nullable|string',
            'reles' => 'nullable|string',
            'temporizadores' => 'nullable|string',
            'contactores' => 'nullable|string',
            'interruptores' => 'nullable|string',
            'conexiones_control' => 'nullable|string',
            'conexiones_potencia' => 'nullable|string',
            'barraje_potencia' => 'nullable|string',
            'barraje_neutros' => 'nullable|string',
            'barraje_tierras' => 'nullable|string',
            'plc' => 'nullable|string',
            'ats' => 'nullable|string',
            'fuentes_auxiliares_check' => 'nullable|string',
            'capacitores' => 'nullable|string',
            'analizador_de_red' => 'nullable|string',
            'Foto_uno_antes' => 'nullable|file|image',
            'Foto_dos_antes' => 'nullable|file|image',
            'Foto_tres_antes' => 'nullable|file|image',
            'actividad_realizada' => 'nullable|string',
            'segundos_tdes' => 'nullable|string',
            'segundos_tdne' => 'nullable|string',
            'segundos_tdtp' => 'nullable|string',
            'segundos_tden' => 'nullable|string',
            'segundos_tdec' => 'nullable|string',
            'alto_voltaje' => 'nullable|string',
            'bajo_voltaje' => 'nullable|string',
            'alta_frecuencia' => 'nullable|string',
            'baja_frecuencia' => 'nullable|string',
            'sobre_carga' => 'nullable|string',
            'sobre_corriente' => 'nullable|string',
            'cables_potencia' => 'nullable|string',
            'terminales' => 'nullable|string',
            'cuepo_contactores' => 'nullable|string',
            'cuerpo_interruptores' => 'nullable|string',
            'transformadores' => 'nullable|string',
            'punto_mas_caliente' => 'nullable|string',
            'observaciones_pruebas' => 'nullable|string',
            'pruebas_con_carga' => 'nullable|string',
            'l1_n' => 'nullable|string',
            'l2_n' => 'nullable|string',
            'l3_n' => 'nullable|string',
            'hz' => 'nullable|string',
            'l1_kw' => 'nullable|string',
            'l2_kw' => 'nullable|string',
            'l3_kw' => 'nullable|string',
            'avg_kw' => 'nullable|string',
            'l1_corriente' => 'nullable|string',
            'l2_corriente' => 'nullable|string',
            'l3_corriente' => 'nullable|string',
            'pf' => 'nullable|string',
            'l1_kva' => 'nullable|string',
            'l2_kva' => 'nullable|string',
            'l3_kva' => 'nullable|string',
            'avg_kva' => 'nullable|string',
            'foto_uno_durante' => 'nullable|file|image',
            'foto_dos_durante' => 'nullable|file|image',
            'foto_tres_durante' => 'nullable|file|image',
            'foto_cuatro_durante' => 'nullable|file|image',
            'foto_cinco_durante' => 'nullable|file|image',
            'foto_seis_durante' => 'nullable|file|image',
            'recomendaciones' => 'nullable|string',
            'control' => 'nullable|string',
            'selector' => 'nullable|string',
            'fuentes_auxiliares_posicion' => 'nullable|string',
            'foto_uno_despues' => 'nullable|file|image',
            'foto_dos_despues' => 'nullable|file|image',
            'foto_tres_despues' => 'nullable|file|image',
            'fecha_solicitud' => 'nullable|date',
            'llegada_tecnico' => 'nullable|string',
            'salida_tecnico' => 'nullable|string',
            'nombre_tecnico' => 'nullable|string',
            'cedula_tecnico' => 'nullable|string',
            'firma_tecnico' => 'nullable|string',
            'nombre_cliente' => 'nullable|string',
            'cedula_cliente' => 'nullable|string',
            'firma_cliente' => 'nullable|string',
            'calificacion_servicio' => 'nullable|string',
        ];
    }
}

